api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "wandini-checkout-validation"
type = "function"
uid = "a19182df-7ed7-2737-740f-46803be2576267dc2982"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
